worldbank/gld

- README.md
Pull request since not allowed to go direct route.
> More Test.

- GLD/PHL/PHL_1997_LFS/PHL_1997_LFS_v01_M_v01_A_I2D2/Programs/PHL_1997_I2D2_LFS.do
- GLD/PHL/PHL_1998_LFS/PHL_1998_LFS_v01_M_v01_A_I2D2/Programs/PHL_1998_I2D2_LFS.do
- GLD/PHL/PHL_1999_LFS/PHL_1999_LFS_v01_M_v01_A_I2D2/Programs/PHL_1999_I2D2_LFS.do
- GLD/PHL/PHL_2000_LFS/PHL_2000_LFS_v01_M_v01_A_I2D2/Programs/PHL_2000_I2D2_LFS.do
- GLD/PHL/PHL_2001_LFS/PHL_2001_LFS_v01_M_v01_A_I2D2/Programs/PHL_2001_I2D2_LFS.do
- GLD/PHL/PHL_2002_LFS/PHL_2002_LFS_v01_M_v01_A_I2D2/Programs/PHL_2002_I2D2_LFS.do
- GLD/PHL/PHL_2003_LFS/PHL_2003_LFS_v01_M_v01_A_I2D2/Programs/PHL_2003_I2D2_LFS.do
- GLD/PHL/PHL_2004_LFS/PHL_2004_LFS_v01_M_v01_A_I2D2/Programs/PHL_2004_I2D2_LFS.do
- GLD/PHL/PHL_2005_LFS/PHL_2005_LFS_v01_M_v01_A_I2D2/Programs/PHL_2005_I2D2_LFS.do
- GLD/PHL/PHL_2006_LFS/PHL_2006_LFS_v01_M_v01_A_I2D2/Programs/PHL_2006_I2D2_LFS.do
- GLD/PHL/PHL_2007_LFS/PHL_2007_LFS_v01_M_v01_A_I2D2/Programs/PHL_2007_I2D2_LFS.do
- GLD/PHL/PHL_2008_LFS/PHL_2008_LFS_v01_M_v01_A_I2D2/Programs/PHL_2008_I2D2_LFS.do
- GLD/PHL/PHL_2009_LFS/PHL_2009_LFS_v01_M_v01_A_I2D2/Programs/PHL_2009_I2D2_LFS.do
- GLD/PHL/PHL_2010_LFS/PHL_2010_LFS_v01_M_v01_A_I2D2/Programs/PHL_2010_I2D2_LFS.do
- GLD/PHL/PHL_2011_LFS/PHL_2011_LFS_v01_M_v01_A_I2D2/Programs/PHL_2011_I2D2_LFS.do
- GLD/PHL/PHL_2012_LFS/PHL_2012_LFS_v01_M_v01_A_I2D2/Programs/PHL_2012_I2D2_LFS.do
- GLD/PHL/PHL_2013_LFS/PHL_2013_LFS_v01_M_v01_A_I2D2/Programs/PHL_2013_I2D2_LFS.do
- GLD/PHL/PHL_2014_LFS/PHL_2014_LFS_v01_M_v01_A_I2D2/Programs/PHL_2014_I2D2_LFS.do
- GLD/PHL/PHL_2015_LFS/PHL_2015_LFS_v01_M_v01_A_I2D2/Programs/PHL_2015_I2D2_LFS.do
- GLD/PHL/PHL_2017_LFS/PHL_2017_LFS_v01_M_v01_A_I2D2/Programs/PHL_2017_I2D2_LFS.do
To examine and fix industry coding across years if necessary.
> fix Industry Codes

- GLD/PHL/PHL_2017_LFS/PHL_2017_LFS_v01_M_v01_A_I2D2/Programs/PHL_2017_I2D2_LFS.do
- GLD/PHL/PHL_2017_LFS/PHL_2017_LFS_v01_M_v01_A_I2D2/Programs/PHL_2017_I2D2_LFS_labels.R
- GLD/PHL/PHL_2017_LFS/PHL_2017_LFS_v01_M_v01_A_I2D2/Programs/README.md
- GLD/PHL/PHL_MAIN.do
informed by #25 , create a working template to incorporate a `.do` file, `iecodebook`, `.R` script workflow. Also include a README that explains
> incorporate multiscript label solution

- GLD/PHL/PHL_MAIN.do
- GLD/PHL/utilities/factor_levels_sandbox.R
- GLD/PHL/utilities/factor_levels_sandbox.Rmd
> Experimental branch/PR to harmonize data labels

- Support/Templates/GLD_Harmonization_Template.do
I changed the "in" to "for", otherwise for some reason the code does not run.
> Loop in section "8.13 labour cleanup"

- Support/Templates/GLD_Harmonization_Template.do
I added a conditional to drop the labels only if the length of the local vector containing the list of value labels is >= 1
> Edit label drop code

- Support/Country Survey Details/PHL/LFS/Rmd/Administrative_Levels.Rmd
- Support/Global/province_label_util.R
With human interventions to check the consistency of labels over time to make sure the make sense, and to determine  the final labels for each item
> Create semi-automated province labelling workflow

- Support/Country Survey Details/PHL/LFS/Administrative_Levels.md
- Support/Country Survey Details/PHL/LFS/Rmd/Administrative_Levels.Rmd
- Support/Country Survey Details/PHL/LFS/Rmd/Industry_Occupation_Codes.Rmd
- Support/Global/international_codes.R
- Support/Global/international_codes_sandbox.R
- main.R
- renv.lock
- renv/activate.R
Create a working version of an output table that matches ISIC codes
> match ISIC codes

- Support/Global/international_codes.R
- Support/Global/read_pdf_table.R
Write a higher-level function that does not require pre-loading of the pdf file into the global environment
> Create higher-level function

- Support/Global/international_codes.R
- Support/Global/read_pdf_table.R
Working function has been created and implemented in `international_codes.R`
> Generalize PDF function

- Support/Global/international_codes.R
- Support/Global/read_pdf_table.R
improve `read_pdf()` to allow for situations where there are sometimes page headers and sometimes not
> page header toggle

- GLD/PHL/PHL_2013_LFS/PHL_2013_LFS_v01_M_v01_A_GLD/Programs/PHL_2013_GLD_LFS.do
- Support/Global/international_codes.R
- Support/Global/read_pdf_table.R
- Support/Global/sandbox1.R
from #103, adjusting the main function to account for rows that actually go together but do not align because the y values differ very slightly
> add fuzzy row match to read_pdf 

- GLD/GLD_I2D2_MAIN.do
- GLD/PHL/PHL_2013_LFS/PHL_2013_LFS_v01_M_v01_A_GLD/Programs/PHL_2013_GLD_LFS.do
- GLD/PHL/PHL_MAIN.do
- Support/Global/best_matches.R
- Support/Global/international_codes.R
- Support/Global/read_pdf_table.R
- Support/Global/sandbox1.R
Create a function that automatically reduces / cleans the "cleaned" version of the `read_pdf()` output. Also fix `read_pdf()` to account for any bugs or errors such as #103
> Create a 1-to-1 match PSIC-isic4 reduced key

- GLD/PHL/PHL_2003_LFS/PHL_2003_LFS_v01_M_v01_A_GLD/Programs/PHL_2003_GLD_LFS.do
the I2D2 version of this code was complicated so create a PR to review specifically...
> recode GLD 2003

- Support/Global/best_matches.R
- Support/Global/correspondance.R
- Support/Global/international_codes.R
- renv.lock
The match score column is wrong. Resources:
- https://dplyr.tidyverse.org/articles/programming.html#data-and-env-variables
> Fix match score of best match function

- GLD/PHL/PHL_2012_LFS/PHL_2012_LFS_v01_M_v01_A_GLD/Programs/PHL_2012_GLD_LFS.do
- GLD/PHL/PHL_2013_LFS/PHL_2013_LFS_v01_M_v01_A_GLD/Programs/PHL_2013_GLD_LFS.do
- GLD/PHL/PHL_2017_LFS/PHL_2017_LFS_v01_M_v01_A_GLD/Programs/PHL_2017_GLD_LFS.do
- GLD/PHL/PHL_MAIN.do
- GLD/PHL/utilities/issue117_check.do
- Support/Global/correspondance.R
- Support/Global/international_codes.R
The PR will address #117 by adjusting the corresp() function to ensure a realistic match percentage between country code and international code
> Resolve errors in ISIC and ISCO keys

- Support/Country Survey Details/PHL/LFS/Rmd/Education_Levels.Rmd
- Support/Global/ISCED_mapping.R
- Support/Global/valtab.R
Decide whether or not to create a key for ISCED data and, if so, make the key
> Resolve ISCED variables

- GLD/PHL/PHL_1997_LFS/PHL_1997_LFS_v01_M_v01_A_GLD/Programs/PHL_1997_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_1998_LFS/PHL_1998_LFS_v01_M_v01_A_GLD/Programs/PHL_1998_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_1999_LFS/PHL_1999_LFS_v01_M_v01_A_GLD/Programs/PHL_1999_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_2000_LFS/PHL_2000_LFS_v01_M_v01_A_GLD/Programs/PHL_2000_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_2001_LFS/PHL_2001_LFS_v01_M_v01_A_GLD/Programs/PHL_2001_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_2002_LFS/PHL_2002_LFS_v01_M_v01_A_GLD/Programs/PHL_2002_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_2003_LFS/PHL_2003_LFS_v01_M_v01_A_GLD/Programs/PHL_2003_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_2004_LFS/PHL_2004_LFS_v01_M_v01_A_GLD/Programs/PHL_2004_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_2005_LFS/PHL_2005_LFS_v01_M_v01_A_GLD/Programs/PHL_2005_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_2006_LFS/PHL_2006_LFS_v01_M_v01_A_GLD/Programs/PHL_2006_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_2007_LFS/PHL_2007_LFS_v01_M_v01_A_GLD/Programs/PHL_2007_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_2008_LFS/PHL_2008_LFS_v01_M_v01_A_GLD/Programs/PHL_2008_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_2009_LFS/PHL_2009_LFS_v01_M_v01_A_GLD/Programs/PHL_2009_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_2010_LFS/PHL_2010_LFS_v01_M_v01_A_GLD/Programs/PHL_2010_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_2011_LFS/PHL_2011_LFS_v01_M_v01_A_GLD/Programs/PHL_2011_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_2012_LFS/PHL_2012_LFS_v01_M_v01_A_GLD/Programs/PHL_2012_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_2013_LFS/PHL_2013_LFS_v01_M_v01_A_GLD/Programs/PHL_2013_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_2014_LFS/PHL_2014_LFS_v01_M_v01_A_GLD/Programs/PHL_2014_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_2015_LFS/PHL_2015_LFS_v01_M_v01_A_GLD/Programs/PHL_2015_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_2016_LFS/PHL_2016_LFS_v01_M_v01_A_GLD/Programs/PHL_2016_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_2017_LFS/PHL_2017_LFS_v01_M_v01_A_GLD/Programs/PHL_2017_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_2018_LFS/PHL_2018_LFS_v01_M_v01_A_GLD/Programs/PHL_2018_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_2019_LFS/PHL_2019_LFS_v01_M_v01_A_GLD/Programs/PHL_2019_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_MAIN.do
- Support/Global/label_tools.R
- Support/Q Checks/Helper Programs/Dynamic Quality Checks.R
- renv.lock
following up from #129, add `educat_orig` to all GLD code for PHL
> add educat_orig to PHL

- GLD/PHL/PHL_1997_LFS/PHL_1997_LFS_v01_M_v01_A_GLD/Programs/PHL_1997_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_1998_LFS/PHL_1998_LFS_v01_M_v01_A_GLD/Programs/PHL_1998_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_1999_LFS/PHL_1999_LFS_v01_M_v01_A_GLD/Programs/PHL_1999_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_2000_LFS/PHL_2000_LFS_v01_M_v01_A_GLD/Programs/PHL_2000_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_2001_LFS/PHL_2001_LFS_v01_M_v01_A_GLD/Programs/PHL_2001_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_2002_LFS/PHL_2002_LFS_v01_M_v01_A_GLD/Programs/PHL_2002_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_2003_LFS/PHL_2003_LFS_v01_M_v01_A_GLD/Programs/PHL_2003_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_2004_LFS/PHL_2004_LFS_v01_M_v01_A_GLD/Programs/PHL_2004_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_2005_LFS/PHL_2005_LFS_v01_M_v01_A_GLD/Programs/PHL_2005_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_2006_LFS/PHL_2006_LFS_v01_M_v01_A_GLD/Programs/PHL_2006_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_2007_LFS/PHL_2007_LFS_v01_M_v01_A_GLD/Programs/PHL_2007_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_2008_LFS/PHL_2008_LFS_v01_M_v01_A_GLD/Programs/PHL_2008_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_2009_LFS/PHL_2009_LFS_v01_M_v01_A_GLD/Programs/PHL_2009_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_2010_LFS/PHL_2010_LFS_v01_M_v01_A_GLD/Programs/PHL_2010_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_2011_LFS/PHL_2011_LFS_v01_M_v01_A_GLD/Programs/PHL_2011_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_2012_LFS/PHL_2012_LFS_v01_M_v01_A_GLD/Programs/PHL_2012_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_2013_LFS/PHL_2013_LFS_v01_M_v01_A_GLD/Programs/PHL_2013_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_2014_LFS/PHL_2014_LFS_v01_M_v01_A_GLD/Programs/PHL_2014_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_2015_LFS/PHL_2015_LFS_v01_M_v01_A_GLD/Programs/PHL_2015_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_2016_LFS/PHL_2016_LFS_v01_M_v01_A_GLD/Programs/PHL_2016_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_2017_LFS/PHL_2017_LFS_v01_M_v01_A_GLD/Programs/PHL_2017_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_2018_LFS/PHL_2018_LFS_v01_M_v01_A_GLD/Programs/PHL_2018_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_2019_LFS/PHL_2019_LFS_v01_M_v01_A_GLD/Programs/PHL_2019_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_MAIN.do
- Support/Global/label_tools.R
- Support/Q Checks/Helper Programs/Dynamic Quality Checks.R
- renv.lock
Improvements to pass Dynamic and Static Quality Checks for GLD
> Pass PHL quality checks

- GLD/PHL/PHL_1997_LFS/PHL_1997_LFS_v01_M_v01_A_I2D2/Programs/PHL_1997_I2D2_LFS.do
- GLD/PHL/PHL_1998_LFS/PHL_1998_LFS_v01_M_v01_A_I2D2/Programs/PHL_1998_I2D2_LFS.do
- GLD/PHL/PHL_1999_LFS/PHL_1999_LFS_v01_M_v01_A_I2D2/Programs/PHL_1999_I2D2_LFS.do
- GLD/PHL/PHL_2000_LFS/PHL_2000_LFS_v01_M_v01_A_I2D2/Programs/PHL_2000_I2D2_LFS.do
- GLD/PHL/PHL_2001_LFS/PHL_2001_LFS_v01_M_v01_A_I2D2/Programs/PHL_2001_I2D2_LFS.do
- GLD/PHL/PHL_2002_LFS/PHL_2002_LFS_v01_M_v01_A_I2D2/Programs/PHL_2002_I2D2_LFS.do
- GLD/PHL/PHL_2003_LFS/PHL_2003_LFS_v01_M_v01_A_I2D2/Programs/PHL_2003_I2D2_LFS_APR.do
- GLD/PHL/PHL_2003_LFS/PHL_2003_LFS_v01_M_v01_A_I2D2/Programs/PHL_2003_I2D2_LFS_JAN.do
- GLD/PHL/PHL_2003_LFS/PHL_2003_LFS_v01_M_v01_A_I2D2/Programs/PHL_2003_I2D2_LFS_JUL.do
- GLD/PHL/PHL_2003_LFS/PHL_2003_LFS_v01_M_v01_A_I2D2/Programs/PHL_2003_I2D2_LFS_OCT.do
- GLD/PHL/PHL_2003_LFS/PHL_2003_LFS_v01_M_v01_A_I2D2/Programs/PHL_2003_I2D2_LFS_archive.do
- GLD/PHL/PHL_2004_LFS/PHL_2004_LFS_v01_M_v01_A_I2D2/Programs/PHL_2004_I2D2_LFS.do
- GLD/PHL/PHL_2005_LFS/PHL_2005_LFS_v01_M_v01_A_I2D2/Programs/PHL_2005_I2D2_LFS.do
- GLD/PHL/PHL_2006_LFS/PHL_2006_LFS_v01_M_v01_A_I2D2/Programs/PHL_2006_I2D2_LFS.do
- GLD/PHL/PHL_2007_LFS/PHL_2007_LFS_v01_M_v01_A_I2D2/Programs/PHL_2007_I2D2_LFS.do
- GLD/PHL/PHL_2008_LFS/PHL_2008_LFS_v01_M_v01_A_I2D2/Programs/PHL_2008_I2D2_LFS.do
- GLD/PHL/PHL_2009_LFS/PHL_2009_LFS_v01_M_v01_A_I2D2/Programs/PHL_2009_I2D2_LFS.do
- GLD/PHL/PHL_2010_LFS/PHL_2010_LFS_v01_M_v01_A_I2D2/Programs/PHL_2010_I2D2_LFS.do
- GLD/PHL/PHL_2011_LFS/PHL_2011_LFS_v01_M_v01_A_I2D2/Programs/PHL_2011_I2D2_LFS.do
- GLD/PHL/PHL_2012_LFS/PHL_2012_LFS_v01_M_v01_A_I2D2/Programs/PHL_2012_I2D2_LFS.do
- GLD/PHL/PHL_2013_LFS/PHL_2013_LFS_v01_M_v01_A_I2D2/Programs/PHL_2013_I2D2_LFS.do
- GLD/PHL/PHL_2014_LFS/PHL_2014_LFS_v01_M_v01_A_I2D2/Programs/PHL_2014_I2D2_LFS.do
- GLD/PHL/PHL_2015_LFS/PHL_2015_LFS_v01_M_v01_A_I2D2/Programs/PHL_2015_I2D2_LFS.do
- GLD/PHL/PHL_2016_LFS/PHL_2016_LFS_v01_M_v01_A_I2D2/Programs/PHL_2016_I2D2_LFS.do
- GLD/PHL/PHL_2017_LFS/PHL_2017_LFS_v01_M_v01_A_I2D2/Programs/PHL_2017_I2D2_LFS.do
- GLD/PHL/PHL_2018_LFS/PHL_2018_LFS_v01_M_v01_A_I2D2/Programs/PHL_2018_I2D2_LFS.do
- GLD/PHL/PHL_2019_LFS/PHL_2019_LFS_v01_M_v01_A_I2D2/Programs/PHL_2019_I2D2_LFS.do
adjust code for unitwage* variables in I2D2 as necessary
> Phl i2d2 recode

- Support/Country Survey Details/PHL/LFS/1.--Introduction-to-PHL.md
- Support/Country Survey Details/PHL/LFS/Rmd/1.  Introduction to PHL.Rmd
With help from[ this blog post](https://github.blog/2013-01-31-relative-links-in-markup-files/) (many thanks!)
> Attempt 2 with relative branch links

- .gitignore
- gld.Rproj
- renv.lock
- renv/.gitignore
- renv/activate.R
In response to request from #131, this is what a start at adding an renv to the main branch and syncing the gitignores with a current .gitignore might look like.
> Sample Add renv to Main Branch

- GLD/PHL/PHL_1997_LFS/PHL_1997_LFS_v01_M_v01_A_GLD/Programs/PHL_1997_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_1998_LFS/PHL_1998_LFS_v01_M_v01_A_GLD/Programs/PHL_1998_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_1999_LFS/PHL_1999_LFS_v01_M_v01_A_GLD/Programs/PHL_1999_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_2000_LFS/PHL_2000_LFS_v01_M_v01_A_GLD/Programs/PHL_2000_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_2001_LFS/PHL_2001_LFS_v01_M_v01_A_GLD/Programs/PHL_2001_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_2002_LFS/PHL_2002_LFS_v01_M_v01_A_GLD/Programs/PHL_2002_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_2003_LFS/PHL_2003_LFS_v01_M_v01_A_GLD/Programs/PHL_2003_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_2004_LFS/PHL_2004_LFS_v01_M_v01_A_GLD/Programs/PHL_2004_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_2005_LFS/PHL_2005_LFS_v01_M_v01_A_GLD/Programs/PHL_2005_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_2006_LFS/PHL_2006_LFS_v01_M_v01_A_GLD/Programs/PHL_2006_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_2007_LFS/PHL_2007_LFS_v01_M_v01_A_GLD/Programs/PHL_2007_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_2008_LFS/PHL_2008_LFS_v01_M_v01_A_GLD/Programs/PHL_2008_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_2009_LFS/PHL_2009_LFS_v01_M_v01_A_GLD/Programs/PHL_2009_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_2010_LFS/PHL_2010_LFS_v01_M_v01_A_GLD/Programs/PHL_2010_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_2011_LFS/PHL_2011_LFS_v01_M_v01_A_GLD/Programs/PHL_2011_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_2012_LFS/PHL_2012_LFS_v01_M_v01_A_GLD/Programs/PHL_2012_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_2013_LFS/PHL_2013_LFS_v01_M_v01_A_GLD/Programs/PHL_2013_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_2014_LFS/PHL_2014_LFS_v01_M_v01_A_GLD/Programs/PHL_2014_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_2015_LFS/PHL_2015_LFS_v01_M_v01_A_GLD/Programs/PHL_2015_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_2016_LFS/PHL_2016_LFS_v01_M_v01_A_GLD/Programs/PHL_2016_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_2017_LFS/PHL_2017_LFS_v01_M_v01_A_GLD/Programs/PHL_2017_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_2018_LFS/PHL_2018_LFS_v01_M_v01_A_GLD/Programs/PHL_2018_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_2019_LFS/PHL_2019_LFS_v01_M_v01_A_GLD/Programs/PHL_2019_LFS_v01_M_v01_A_GLD_ALL.do
- Support/Country Survey Details/PHL/LFS/Rmd/Weights_PSA_Checks.Rmd
- Support/Global/import_surveys.R
- Support/Global/weights_analysis.R
- Support/Global/weights_per_HH.R
- Support/Templates/1. Introduction to [Survey Acronym].md
- renv.lock
Various major and minor revision to PHL GLD code based on static checks and miscellaneous tasks.
> Remaining GLD revisions for PHL

- GLD/PHL/PHL_1997_LFS/PHL_1997_LFS_v01_M_v01_A_GLD/Programs/PHL_1997_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_1998_LFS/PHL_1998_LFS_v01_M_v01_A_GLD/Programs/PHL_1998_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_1999_LFS/PHL_1999_LFS_v01_M_v01_A_GLD/Programs/PHL_1999_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_2000_LFS/PHL_2000_LFS_v01_M_v01_A_GLD/Programs/PHL_2000_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_2001_LFS/PHL_2001_LFS_v01_M_v01_A_GLD/Programs/PHL_2001_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_2002_LFS/PHL_2002_LFS_v01_M_v01_A_GLD/Programs/PHL_2002_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_2003_LFS/PHL_2003_LFS_v01_M_v01_A_GLD/Programs/PHL_2003_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_2004_LFS/PHL_2004_LFS_v01_M_v01_A_GLD/Programs/PHL_2004_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_2005_LFS/PHL_2005_LFS_v01_M_v01_A_GLD/Programs/PHL_2005_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_2006_LFS/PHL_2006_LFS_v01_M_v01_A_GLD/Programs/PHL_2006_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_2007_LFS/PHL_2007_LFS_v01_M_v01_A_GLD/Programs/PHL_2007_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_2008_LFS/PHL_2008_LFS_v01_M_v01_A_GLD/Programs/PHL_2008_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_2009_LFS/PHL_2009_LFS_v01_M_v01_A_GLD/Programs/PHL_2009_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_2010_LFS/PHL_2010_LFS_v01_M_v01_A_GLD/Programs/PHL_2010_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_2011_LFS/PHL_2011_LFS_v01_M_v01_A_GLD/Programs/PHL_2011_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_2012_LFS/PHL_2012_LFS_v01_M_v01_A_GLD/Programs/PHL_2012_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_2013_LFS/PHL_2013_LFS_v01_M_v01_A_GLD/Programs/PHL_2013_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_2014_LFS/PHL_2014_LFS_v01_M_v01_A_GLD/Programs/PHL_2014_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_2015_LFS/PHL_2015_LFS_v01_M_v01_A_GLD/Programs/PHL_2015_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_2016_LFS/PHL_2016_LFS_v01_M_v01_A_GLD/Programs/PHL_2016_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_2019_LFS/PHL_2019_LFS_v01_M_v01_A_GLD/Programs/PHL_2019_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PHL/PHL_MAIN.do
Fix a few variable type errors that generated missing variables as the incorrect type (numeric) instead of the correct type (string)
> Fix miscellaneous variable types

- Support/Country Survey Details/PHL/LFS/1.--Introduction-to-PHL.md
- Support/Country Survey Details/PHL/LFS/Rmd/weights_methodology.Rmd
- Support/Global/population_lfp.R
Resolve #144, change the weight variables in the stata code, and provide proper documentation
> Resolve weight variable discrepancy and document it

- GLD/ZWE/ZWE_2019_LFCLS/ZWE_2019_LFCLS_v01_M_v01_A_GLD/GLD_Harmonization_Template.do
- GLD/ZWE/ZWE_2019_LFCLS/ZWE_2019_LFCLS_v01_M_v01_A_I2D2/placeholder.md
add blank template for gld and placeholder md for I2D2
> Add folder structure for 2019 ZWE

- GLD/MEX/MEX_2005_ENOE/MEX_2005_ENOE_v01_M_v01_A_GLD/Programs/MEX_2005_ENOE_V01_M_V01_A_GLD_ALL.do
- GLD/MEX/MEX_2006_ENOE/MEX_2006_ENOE_v01_M_v01_A_GLD/Programs/MEX_2006_ENOE_V01_M_V01_A_GLD_ALL.do
- GLD/MEX/MEX_2007_ENOE/MEX_2007_ENOE_v01_M_v01_A_GLD/Programs/MEX_2007_ENOE_V01_M_V01_A_GLD_ALL.do
- GLD/MEX/MEX_2008_ENOE/MEX_2008_ENOE_v01_M_v01_A_GLD/Programs/MEX_2008_ENOE_V01_M_V01_A_GLD_ALL.do
- GLD/MEX/MEX_2009_ENOE/MEX_2009_ENOE_v01_M_v01_A_GLD/Programs/MEX_2009_ENOE_V01_M_V01_A_GLD_ALL.do
- GLD/MEX/MEX_2010_ENOE/MEX_2010_ENOE_v01_M_v01_A_GLD/Programs/MEX_2010_ENOE_V01_M_V01_A_GLD_ALL.do
- GLD/MEX/MEX_2011_ENOE/MEX_2011_ENOE_v01_M_v01_A_GLD/Programs/MEX_2011_ENOE_v01_M_v01_A_GLD_ALL.do
- GLD/MEX/MEX_2012_ENOE/MEX_2012_ENOE_v01_M_v01_A_GLD/Programs/MEX_2012_ENOE_v01_M_v01_A_GLD_ALL.do
- GLD/MEX/MEX_2013_ENOE/MEX_2013_ENOE_v01_M_v01_A_GLD/Programs/MEX_2013_ENOE_v01_M_v01_A_GLD_ALL.do
- GLD/MEX/MEX_2014_ENOE/MEX_2014_ENOE_v01_M_v01_A_GLD/Programs/MEX_2014_ENOE_V01_M_V01_A_GLD_ALL.do
- GLD/MEX/MEX_2015_ENOE/MEX_2015_ENOE_v01_M_v01_A_GLD/Programs/MEX_2015_ENOE_V01_M_V01_A_GLD_ALL.do
- GLD/MEX/MEX_2016_ENOE/MEX_2016_ENOE_v01_M_v01_A_GLD/Programs/MEX_2016_ENOE_V01_M_V01_A_GLD_ALL.do
- GLD/MEX/MEX_2017_ENOE/MEX_2017_ENOE_v01_M_v01_A_GLD/Programs/MEX_2017_ENOE_V01_M_V01_A_GLD_ALL.do
- GLD/MEX/MEX_2018_ENOE/MEX_2018_ENOE_v01_M_v01_A_GLD/Programs/MEX_2018_ENOE_V01_M_V01_A_GLD_ALL.do
- GLD/MEX/MEX_2019_ENOE/MEX_2019_ENOE_v01_M_v01_A_GLD/Programs/MEX_2019_ENOE_V01_M_V01_A_GLD_ALL.do
- GLD/MEX/MEX_2020_ENOE/MEX_2020_ENOE_v01_M_v01_A_GLD/Programs/MEX_2020_ENOE_V01_M_V01_A_GLD_ALL.do
Hi Mario, 
As requested, here are the corrections for MEX,
Best,
Alexandra
> Corrections MEX jan 2022

- GLD/MEX/MEX_2005_ENOE/MEX_2005_ENOE_v01_M_v01_A_GLD/Programs/MEX_2005_ENOE_V01_M_V01_A_GLD_ALL.do
- GLD/MEX/MEX_2006_ENOE/MEX_2006_ENOE_v01_M_v01_A_GLD/Programs/MEX_2006_ENOE_V01_M_V01_A_GLD_ALL.do
- GLD/MEX/MEX_2007_ENOE/MEX_2007_ENOE_v01_M_v01_A_GLD/Programs/MEX_2007_ENOE_V01_M_V01_A_GLD_ALL.do
- GLD/MEX/MEX_2008_ENOE/MEX_2008_ENOE_v01_M_v01_A_GLD/Programs/MEX_2008_ENOE_V01_M_V01_A_GLD_ALL.do
- GLD/MEX/MEX_2009_ENOE/MEX_2009_ENOE_v01_M_v01_A_GLD/Programs/MEX_2009_ENOE_V01_M_V01_A_GLD_ALL.do
- GLD/MEX/MEX_2010_ENOE/MEX_2010_ENOE_v01_M_v01_A_GLD/Programs/MEX_2010_ENOE_V01_M_V01_A_GLD_ALL.do
- GLD/MEX/MEX_2011_ENOE/MEX_2011_ENOE_v01_M_v01_A_GLD/Programs/MEX_2011_ENOE_v01_M_v01_A_GLD_ALL.do
- GLD/MEX/MEX_2012_ENOE/MEX_2012_ENOE_v01_M_v01_A_GLD/Programs/MEX_2012_ENOE_v01_M_v01_A_GLD_ALL.do
- GLD/MEX/MEX_2013_ENOE/MEX_2013_ENOE_v01_M_v01_A_GLD/Programs/MEX_2013_ENOE_v01_M_v01_A_GLD_ALL.do
- GLD/MEX/MEX_2014_ENOE/MEX_2014_ENOE_v01_M_v01_A_GLD/Programs/MEX_2014_ENOE_V01_M_V01_A_GLD_ALL.do
- GLD/MEX/MEX_2015_ENOE/MEX_2015_ENOE_v01_M_v01_A_GLD/Programs/MEX_2015_ENOE_V01_M_V01_A_GLD_ALL.do
- GLD/MEX/MEX_2016_ENOE/MEX_2016_ENOE_v01_M_v01_A_GLD/Programs/MEX_2016_ENOE_V01_M_V01_A_GLD_ALL.do
- GLD/MEX/MEX_2017_ENOE/MEX_2017_ENOE_v01_M_v01_A_GLD/Programs/MEX_2017_ENOE_V01_M_V01_A_GLD_ALL.do
- GLD/MEX/MEX_2018_ENOE/MEX_2018_ENOE_v01_M_v01_A_GLD/Programs/MEX_2018_ENOE_V01_M_V01_A_GLD_ALL.do
- GLD/MEX/MEX_2019_ENOE/MEX_2019_ENOE_v01_M_v01_A_GLD/Programs/MEX_2019_ENOE_V01_M_V01_A_GLD_ALL.do
- GLD/MEX/MEX_2020_ENOE/MEX_2020_ENOE_v01_M_v01_A_GLD/Programs/MEX_2020_ENOE_V01_M_V01_A_GLD_ALL.do
As requested I corrected the subnatid1 issue that occurred in all files.
Best,
Alexandra
> Mex corrections2

- Support/Country Survey Details/TUR/HLFS/1. Introduction to HLFS.md
Short paragraph to introduce Isco and isic to the user
> Introduction short par

- Support/D - Q Checks/Helper Programs/GLD Static Q-Checks.do
- Support/D - Q Checks/Helper Programs/Helper_GLD_VarLists.do
- Support/D - Q Checks/Template - Run all Q-Checks.do
Update q checks to
1) evaluate version in file name matches version in variables
2) evaluate if industry_orig present for cases when industrycat10 is not
> Update q checks

- Support/D - Q Checks/Helper Programs/Helper_GLD_VarLists.do
Change from ending on 
industrycat10_2_year"""'
to ending on 
industrycat10_2_year""'
> Update global industrial alingment

- Support/D - Q Checks/Helper Programs/GLD Static Q-Checks.do
- Support/D - Q Checks/Template - Run all Q-Checks.do
Please note I changed this because it was missing and all the files ended up in a different folder.
> Missing Output folder in the path out

- GLD/ZAF/ZAF_2010_QLFS/ZAF_2010_QLFS_v01_M_v02_A_GLD/Programs/ZAF_2010_QLFS_v01_M_v02_A_GLD_ALL.do
- GLD/ZAF/ZAF_2011_QLFS/ZAF_2011_QLFS_v01_M_v02_A_GLD/Programs/ZAF_2011_QLFS_v01_M_v02_A_GLD_ALL.do
- GLD/ZAF/ZAF_2012_QLFS/ZAF_2012_QLFS_v01_M_v02_A_GLD/Programs/ZAF_2012_QLFS_v01_M_v02_A_GLD_ALL.do
- GLD/ZAF/ZAF_2013_QLFS/ZAF_2013_QLFS_v01_M_v02_A_GLD/Programs/ZAF_2013_QLFS_v01_M_v02_A_GLD_ALL.do
- GLD/ZAF/ZAF_2014_QLFS/ZAF_2014_QLFS_v01_M_v02_A_GLD/Programs/ZAF_2014_QLFS_v01_M_v02_A_GLD_ALL.do
- GLD/ZAF/ZAF_2015_QLFS/ZAF_2015_QLFS_v01_M_v02_A_GLD/Programs/ZAF_2015_QLFS_v01_M_v02_A_GLD_ALL.do
- GLD/ZAF/ZAF_2016_QLFS/ZAF_2016_QLFS_v01_M_v02_A_GLD/Programs/ZAF_2016_QLFS_v01_M_v02_A_GLD_ALL.do
- GLD/ZAF/ZAF_2017_QLFS/ZAF_2017_QLFS_v01_M_v02_A_GLD/Programs/ZAF_2017_QLFS_v01_M_v02_A_GLD_ALL.do
- GLD/ZAF/ZAF_2018_QLFS/ZAF_2018_QLFS_v01_M_v02_A_GLD/Programs/ZAF_2018_QLFS_v01_M_v02_A_GLD_ALL.do
- GLD/ZAF/ZAF_2019_QLFS/ZAF_2019_QLFS_v01_M_v02_A_GLD/Programs/ZAF_2019_QLFS_v01_M_v02_A_GLD_ALL.do
Hi @Junying-T pull request #243 looks good, but I had some slight deviations in it. Especially there was also a "copy" 2008 file
I have done it through this process on a copy I just made from main this morning. Please give it a quick look and accept. If OK then also delete this branch (zaf-patch) and close your original #243 request.
> Add ZAF wage

- Support/D - Q Checks/Template - Run all Q-Checks.do
Use generic, explained paths not specific cases from past use cases
> Changes to paths

- Support/D - Q Checks/Helper Programs/GLD Static Q-Checks.do
read isic version relies on var isic_version to be in the data. Create a capture to run it only if present, skip otherwise as it would give an error
> Read ISIC version only if isic data there

- Support/D - Q Checks/Helper Programs/GLD Static Q-Checks.do
- Support/D - Q Checks/Helper Programs/Helper_GLD_VarLists.do
Added checks to be able to detect:
* whether code is in ISCO universe
* if there is wage info there needs to be unitwage info and viceversa
> Add isco, wage check

- GLD/CHL/CHL_1990_CASEN/CHL_1990_CASEN_V01_M_V02_A_GLD/Programs/CHL_1990_CASEN_V01_M_V02_A_GLD_ALL.do
- GLD/CHL/CHL_1992_CASEN/CHL_1992_CASEN_V01_M_V02_A_GLD/Programs/CHL_1992_CASEN_V01_M_V02_A_GLD_ALL.do
- GLD/CHL/CHL_1994_CASEN/CHL_1994_CASEN_V01_M_V02_A_GLD/Programs/CHL_1994_CASEN_V01_M_V02_A_GLD_ALL.do
- GLD/CHL/CHL_1996_CASEN/CHL_1996_CASEN_V01_M_V02_A_GLD/Programs/CHL_1996_CASEN_V01_M_V02_A_GLD_ALL.do
- GLD/CHL/CHL_1998_CASEN/CHL_1998_CASEN_V01_M_V02_A_GLD/Programs/CHL_1998_CASEN_V01_M_V02_A_GLD_ALL.do
- GLD/CHL/CHL_2000_CASEN/CHL_2000_CASEN_V01_M_V02_A_GLD/Programs/CHL_2000_CASEN_V01_M_V02_A_GLD_ALL.do
- GLD/CHL/CHL_2003_CASEN/CHL_2003_CASEN_V01_M_V02_A_GLD/Programs/CHL_2003_CASEN_V01_M_V02_A_GLD_ALL.do
- GLD/CHL/CHL_2006_CASEN/CHL_2006_CASEN_V01_M_V02_A_GLD/Programs/CHL_2006_CASEN_V01_M_V02_A_GLD_ALL.do
- GLD/CHL/CHL_2009_CASEN/CHL_2009_CASEN_V01_M_V02_A_GLD/Programs/CHL_2009_CASEN_V01_M_V02_A_GLD_ALL.do
- GLD/CHL/CHL_2011_CASEN/CHL_2011_CASEN_V01_M_V02_A_GLD/Programs/CHL_2011_CASEN_V01_M_V02_A_GLD_ALL.do
- GLD/CHL/CHL_2013_CASEN/CHL_2013_CASEN_V01_M_V02_A_GLD/Programs/CHL_2013_CASEN_V01_M_V02_A_GLD_ALL.do
- GLD/CHL/CHL_2015_CASEN/CHL_2015_CASEN_V01_M_V02_A_GLD/Programs/CHL_2015_CASEN_V01_M_V02_A_GLD_ALL.do
- GLD/CHL/CHL_2017_CASEN/CHL_2017_CASEN_V01_M_V02_A_GLD/Programs/CHL_2017_CASEN_V01_M_V02_A_GLD_ALL.do
Hi @gronert-m , 
As discussed the pull request for main of CHL V2.
Please let me know if there is anything else needed from my end.
Best,
Alexandra
> Version 2 CHL

- GLD/PAK/PAK_2007_LFS/PAK_2007_LFS_v01_M_v01_A_GLD/Programs/PAK_2007_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PAK/PAK_2008_LFS/PAK_2008_LFS_v01_M_v01_A_GLD/Programs/PAK_2008_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PAK/PAK_2010_LFS/PAK_2010_LFS_v01_M_v01_A_GLD/Programs/PAK_2010_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PAK/PAK_2012_LFS/PAK_2012_LFS_v01_M_v01_A_GLD/Programs/PAK_2012_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PAK/PAK_2013_LFS/PAK_2013_LFS_v01_M_v01_A_GLD/Programs/PAK_2013_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PAK/PAK_2014_LFS/PAK_2014_LFS_v01_M_v01_A_GLD/Programs/PAK_2014_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PAK/PAK_2017_LFS/PAK_2017_LFS_v01_M_v01_A_GLD/Programs/PAK_2017_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PAK/PAK_2018_LFS/PAK_2018_LFS_v01_M_v01_A_GLD/Programs/PAK_2018_LFS_v01_M_v01_A_GLD_ALL.do
- GLD/PAK/PAK_2020_LFS/PAK_2020_LFS_v01_M_v01_A_GLD/Programs/PAK_2020_LFS_v01_M_v01_A_GLD_ALL.do
@gronert-m Hi Mario,
Some years' lstatus and underemployment have been corrected. Please check it and merge it into the main branch. Thanks!
> Pak patch isic

- Support/B - Country Survey Details/MEX/ENOE/Correspondence_NAICS_ISIC.md
- Support/Z - Other Tools/ISIC ISCO universe check/int_classif_universe.ado
* Correction in NAICS to ISIC text
* ISIC/ISCO Universe function updated to  exit program smoothly if there are no errors.
> two small updates

- GLD/CHL/CHL_1992_CASEN/CHL_1992_CASEN_V01_M_V03_A_GLD/Programs/CHL_1992_CASEN_V01_M_V03_A_GLD_ALL.do
- GLD/CHL/CHL_1994_CASEN/CHL_1994_CASEN_V01_M_V03_A_GLD/Programs/CHL_1994_CASEN_V01_M_V03_A_GLD_ALL.do
- GLD/CHL/CHL_1996_CASEN/CHL_1996_CASEN_V01_M_V03_A_GLD/Programs/CHL_1996_CASEN_V01_M_V03_A_GLD_ALL.do
The update requested for CHL V3,
Best,
> changes industycat_isic 1992-1996

- Support/B - Country Survey Details/EGY/LFS/1. Introduction to LFS.md
Kindly review the two lines I am proposing.
Best,
Alexandra
> two lines at the end

- Support/D - Q Checks/Helper Programs/GLD Static Q-Checks.do
Hi @gronert-m 
Please, can you accept this change so we can use it in the qchecks template.
Thanks a lot,
Best,
Alexandra
> Fix for java issue

- GLD/IDN/IDN_2019_SAKERNAS/IDN_2019_Sakernas_v02_M_v01_A_GLD/Programs/IDN_2019_Sakernas_v02_M_v01_A_GLD_ALL.do
Hi Mario @gronert-m,
I have updated `industrycat10` in IDN 2019 using `industrycat_orig`. You may now proceed with merging.
> Update `industrycat10` in 2019

- Support/D - Q Checks/Helper Programs/Helper_GLD_VarLists.do
occup_skill also should be checked to see if values are either 1,2,3 or missing
> Include occup_skill in check for cat 1/3 vars

- GLD/COL/COL_2009_GEIH/COL_2009_GEIH_V01_M_V02_A_GLD/Programs/COL_2009_GEIH_V01_M_V02_A_GLD.do
- GLD/COL/COL_2010_GEIH/COL_2010_GEIH_V01_M_V02_A_GLD/Programs/COL_2010_GEIH_V01_M_V02_A_GLD.do
- GLD/COL/COL_2011_GEIH/COL_2011_GEIH_V01_M_V02_A_GLD/Programs/COL_2011_GEIH_V01_M_V02_A_GLD.do
- GLD/COL/COL_2012_GEIH/COL_2012_GEIH_V01_M_V02_A_GLD/Programs/COL_2012_GEIH_V01_M_V02_A_GLD.do
- GLD/COL/COL_2013_GEIH/COL_2013_GEIH_V01_M_V02_A_GLD/Programs/COL_2013_GEIH_V01_M_V02_A_GLD.do
- GLD/COL/COL_2014_GEIH/COL_2014_GEIH_V01_M_V02_A_GLD/Programs/COL_2014_GEIH_V01_M_V02_A_GLD.do
- GLD/COL/COL_2015_GEIH/COL_2015_GEIH_V01_M_V02_A_GLD/Programs/COL_2015_GEIH_V01_M_V02_A_GLD.do
- GLD/COL/COL_2016_GEIH/COL_2016_GEIH_V01_M_V02_A_GLD/Programs/COL_2016_GEIH_V01_M_V02_A_GLD.do
- GLD/COL/COL_2017_GEIH/COL_2017_GEIH_V01_M_V02_A_GLD/Programs/COL_2017_GEIH_V01_M_V02_A_GLD.do
- GLD/COL/COL_2018_GEIH/COL_2018_GEIH_V01_M_V02_A_GLD/Programs/COL_2018_GEIH_V01_M_V02_A_GLD.do
- GLD/COL/COL_2019_GEIH/COL_2019_GEIH_V01_M_V02_A_GLD/Programs/COL_2019_GEIH_V01_M_V02_A_GLD.do
- GLD/COL/COL_2020_GEIH/COL_2020_GEIH_V01_M_V02_A_GLD/Programs/COL_2020_GEIH_V01_M_V02_A_GLD.do
- GLD/COL/COL_2021_GEIH/COL_2021_GEIH_V01_M_V02_A_GLD/Programs/COL_2021_GEIH_V01_M_V02_A_GLD.do
As requested I updated the versions of COL for the variables occur_skills and veralt.
Best,
Alexandra
> v2 col 2009-2021

- GLD/COL/COL_2012_GEIH/COL_2012_GEIH_V01_M_V02_A_GLD/Programs/COL_2012_GEIH_V01_M_V02_A_GLD.do
- GLD/THA/THA_1998_LFS-Q2/THA_1998_LFS-Q2_v01_M_v02_A_GLD/Programs/THA_1998_LFS-Q2_v01_M_v02_A_GLD_ALL.do
Two surveys did not have properly formatted version control tags. Corrected
> Patch of version control tags

- GLD/CHL/CHL_1990_CASEN/CHL_1990_CASEN_V01_M_V03_A_GLD/Programs/CHL_1990_CASEN_V01_M_V03_A_GLD_ALL.do
- GLD/CHL/CHL_1992_CASEN/CHL_1992_CASEN_V01_M_V04_A_GLD/Programs/CHL_1992_CASEN_V01_M_V04_A_GLD_ALL.do
- GLD/CHL/CHL_1994_CASEN/CHL_1994_CASEN_V01_M_V04_A_GLD/Programs/CHL_1994_CASEN_V01_M_V04_A_GLD_ALL.do
- GLD/CHL/CHL_1996_CASEN/CHL_1996_CASEN_V01_M_V04_A_GLD/Programs/CHL_1996_CASEN_V01_M_V04_A_GLD_ALL.do
- GLD/CHL/CHL_1998_CASEN/CHL_1998_CASEN_V01_M_V03_A_GLD/Programs/CHL_1998_CASEN_V01_M_V03_A_GLD_ALL.do
- GLD/CHL/CHL_2000_CASEN/CHL_2000_CASEN_V01_M_V03_A_GLD/Programs/CHL_2000_CASEN_V01_M_V03_A_GLD_ALL.do
- GLD/CHL/CHL_2003_CASEN/CHL_2003_CASEN_V01_M_V03_A_GLD/Programs/CHL_2003_CASEN_V01_M_V03_A_GLD_ALL.do
- GLD/CHL/CHL_2009_CASEN/CHL_2009_CASEN_V01_M_V03_A_GLD/Programs/CHL_2009_CASEN_V01_M_V03_A_GLD_ALL.do
- GLD/CHL/CHL_2011_CASEN/CHL_2011_CASEN_V01_M_V04_A_GLD/Programs/CHL_2011_CASEN_V01_M_V04_A_GLD_ALL.do
- GLD/CHL/CHL_2013_CASEN/CHL_2013_CASEN_V01_M_V04_A_GLD/Programs/CHL_2013_CASEN_V01_M_V04_A_GLD_ALL.do
- GLD/CHL/CHL_2015_CASEN/CHL_2015_CASEN_V01_M_V04_A_GLD/Programs/CHL_2015_CASEN_V01_M_V04_A_GLD_ALL.do
- GLD/CHL/CHL_2017_CASEN/CHL_2017_CASEN_V01_M_V04_A_GLD/Programs/CHL_2017_CASEN_V01_M_V04_A_GLD_ALL.do
Hi @gronert-m 
I did the changes in CHL about occup_skill. It should be fine now. Though please note that the range of occupational skills should be 1 to 4 and not 1 to 3. where 4 is armed forces. So I think the checks need to be updated.
Best,
Alexandra
> v03 and v04 chl

- Support/B - Country Survey Details/TUR/HLFS/1. Introduction to HLFS.md
Also change Turkey to Turkiye to reflect official name change
> Amend geographic representative level info

- GLD/BRA/BRA_2012_PNADC/BRA_2012_PNADC_v01_M_v02_A_GLD/Programs/BRA_2012_PNADC_v01_M_v02_A_GLD_ALL.do
- GLD/BRA/BRA_2013_PNADC/BRA_2013_PNADC_v01_M_v02_A_GLD/Programs/BRA_2013_PNADC_v01_M_v02_A_GLD_ALL.do
- GLD/BRA/BRA_2014_PNADC/BRA_2014_PNADC_v01_M_v02_A_GLD/Programs/BRA_2014_PNADC_v01_M_v02_A_GLD_ALL.do
- GLD/BRA/BRA_2015_PNADC/BRA_2015_PNADC_v01_M_v02_A_GLD/Programs/BRA_2015_PNADC_v01_M_v02_A_GLD_ALL.do
- GLD/BRA/BRA_2016_PNADC/BRA_2016_PNADC_v01_M_v02_A_GLD/Programs/BRA_2016_PNADC_v01_M_v02_A_GLD_ALL.do
- GLD/BRA/BRA_2017_PNADC/BRA_2017_PNADC_v01_M_v02_A_GLD/Programs/BRA_2017_PNADC_v01_M_v02_A_GLD_ALL.do
- GLD/BRA/BRA_2018_PNADC/BRA_2018_PNADC_v01_M_v02_A_GLD/Programs/BRA_2018_PNADC_v01_M_v02_A_GLD_ALL.do
- GLD/BRA/BRA_2019_PNADC/BRA_2019_PNADC_v01_M_v02_A_GLD/Programs/BRA_2019_PNADC_v01_M_v02_A_GLD_ALL.do
- GLD/BRA/BRA_2020_PNADC/BRA_2020_PNADC_v01_M_v02_A_GLD/Programs/BRA_2020_PNADC_v01_M_v02_A_GLD_ALL.do
industrycat10 was set to ISIC v3 when it is actually based on Rev 4.
> Update v2 BRA

- GLD/IDN/IDN_2012_SAKERNAS/IDN_2012_SAKERNAS_v02_M_v02_A_GLD/Programs/IDN_2012_Sakernas_v02_M_v02_A_GLD_ALL.do
Was missing in last patch. Additionally, unify folder naming to Uppercase
> Add v02_M_v02_A

- GLD/EGY/EGY_2019_LFS/EGY_2019_LFS_v01_M_v02_A_GLD/Programs/EGY_2019_LFS_V01_M_V02_A_GLD_ALL.do
I made the change requested and checked the file. All the rest seems fine.
Best,
Alexandra
> v2 2019 EGY

- GLD/CHL/CHL_2000_CASEN/CHL_2000_CASEN_V01_M_V04_A_GLD/Programs/CHL_2000_CASEN_V01_M_V04_A_GLD_ALL.do
- GLD/CHL/CHL_2006_CASEN/CHL_2006_CASEN_V01_M_V04_A_GLD/Programs/CHL_2006_CASEN_V01_M_V04_A_GLD_ALL.do
- GLD/CHL/CHL_2009_CASEN/CHL_2009_CASEN_V01_M_V04_A_GLD/Programs/CHL_2009_CASEN_V01_M_V04_A_GLD_ALL.do
I did the changes requested.
Best,
Alexandra
> v4 2000,06,09

- GLD/PAK/PAK_1992_LFS/PAK_1992_LFS_v01_M_v01_A_GLD/Programs/PAK_1992_LFS_v01_M_v01_A_GLD_ALL.do
Change reference from PSCO 1994 to PSCO 1968
> Update PAK 1992 Preamble

- GLD/PAK/PAK_2013_LFS/PAK_2013_LFS_v01_M_v02_A_GLD/Programs/PAK_2013_LFS_v01_M_v02_A_GLD_ALL.do
Hi @gronert-m Mario,
PAK 2013 has been updated as well. It is ready for the merge.
> Pak 0922 patch

- Support/D - Q Checks/Helper programs_1.3/14_missing_GLD.do
This way the numbering of the variables is not changed, just creates in the first loop subsections to treat variables differently.
Your solution is per se correct, but I fear that changing the numbering of files has knock on effects. Also the change is located in one area.
> Alternative to coding of missing issue

- GLD/PAK/PAK_2007_LFS/PAK_2007_LFS_v01_M_v02_A_GLD/Programs/PAK_2007_LFS_v01_M_v02_A_GLD_ALL.do
- GLD/PAK/PAK_2017_LFS/PAK_2017_LFS_v01_M_v02_A_GLD/Programs/PAK_2017_LFS_v01_M_v02_A_GLD_ALL.do
Hi @gronert-m, 
`urban` issue has been fixed and a version 02 of alt of PAK 2017 was created. I checked other years 2017 is the only year with this issue. You can now merge the patch branch to the main and move the v02 folder to the GLD folder.
> Pak patch 11.1

- Support/D - Q Checks/Helper_programs_1.4/B1.04_Format_Checks_GLD.do
> Correct ISIC ISCO code links

- Support/D - Q Checks/Helper_programs_1.4/B5.01_wage_GLD.do
Convert the metric for evaluation (in graph) from mean to median, dataset to look at now has median, mean, p10, p25, p75, p90, and the sample size to be able to evaluate the information more clearly and easily.
> Update wage check

- Support/D - Q Checks/Helper_programs_1.4/B3.01_missing_GLD.do
Block 3 was not robust to some vars not being in the data. Should work now.
> Update missing part

- Support/B - Country Survey Details/IND/EUS/Correspondence_National_International_Classifications.md
Correct a quote falsely referring to 2005 when it was 1968.
> Update correspondence occup

- GLD/TUR/TUR_2004_HLFS/TUR_2004_HLFS_V01_M_V03_A_GLD/Programs/TUR_2004_HLFS_V01_M_V03_A_GLD_ALL.do
Educat4 had slipped through the cracks
> TUR_2004_V03 correct educat

- Support/D - Q Checks/Helper_programs_1.4/B4.01_bivariate_GLD.do
- Support/D - Q Checks/Helper_programs_1.4/B5.01_wage_GLD.do
Checks still broke down if some vars where missing, hopefully not anymore.
> Robustify checks

- Support/D - Q Checks/Single survey checks/Helper_programs_1.4/B1.04_Format_Checks_GLD.do
Link to ISIC and ISCO text files was incorrect after reorganising quality checks
> Update B1.04 link to ISIC, ISCO

- GLD/IDN/IDN_1989_SAKERNAS/IDN_1989_Sakernas_v01_M_v03_A_GLD/Programs/IDN_1989_Sakernas_v01_M_v03_A_GLD_ALL.do
- GLD/IDN/IDN_1990_SAKERNAS/IDN_1990_Sakernas_v01_M_v03_A_GLD/Programs/IDN_1990_Sakernas_v01_M_v03_A_GLD_ALL.do
- GLD/IDN/IDN_1991_SAKERNAS/IDN_1991_Sakernas_v01_M_v03_A_GLD/Programs/IDN_1991_Sakernas_v01_M_v03_A_GLD_ALL.do
- GLD/IDN/IDN_1992_SAKERNAS/IDN_1992_Sakernas_v01_M_v03_A_GLD/Programs/IDN_1992_Sakernas_v01_M_v03_A_GLD_ALL.do
- GLD/IDN/IDN_1993_SAKERNAS/IDN_1993_Sakernas_v01_M_v03_A_GLD/Programs/IDN_1993_Sakernas_v01_M_v03_A_GLD_ALL.do
- GLD/IDN/IDN_1994_SAKERNAS/IDN_1994_Sakernas_v01_M_v05_A_GLD/Programs/IDN_1994_Sakernas_v01_M_v05_A_GLD_ALL.do
- GLD/IDN/IDN_1996_SAKERNAS/IDN_1996_Sakernas_v01_M_v05_A_GLD/Programs/IDN_1996_Sakernas_v01_M_v05_A_GLD_ALL.do
- GLD/IDN/IDN_1997_SAKERNAS/IDN_1997_Sakernas_v01_M_v05_A_GLD/Programs/IDN_1997_Sakernas_v01_M_v05_A_GLD_ALL.do
- GLD/IDN/IDN_1998_SAKERNAS/IDN_1998_Sakernas_v01_M_v05_A_GLD/Programs/IDN_1998_Sakernas_v01_M_v05_A_GLD_ALL.do
- GLD/IDN/IDN_1999_SAKERNAS/IDN_1999_Sakernas_v01_M_v05_A_GLD/Programs/IDN_1999_Sakernas_v01_M_v05_A_GLD_ALL.do
- GLD/IDN/IDN_2000_SAKERNAS/IDN_2000_Sakernas_v01_M_v04_A_GLD/Programs/IDN_2000_Sakernas_v01_M_v04_A_GLD_ALL.do
- GLD/IDN/IDN_2001_SAKERNAS/IDN_2001_Sakernas_v01_M_v04_A_GLD/Programs/IDN_2001_Sakernas_v01_M_v04_A_GLD_ALL.do
- GLD/IDN/IDN_2002_SAKERNAS/IDN_2002_Sakernas_v01_M_v04_A_GLD/Programs/IDN_2002_Sakernas_v01_M_v04_A_GLD_ALL.do
- GLD/IDN/IDN_2003_SAKERNAS/IDN_2003_Sakernas_v01_M_v04_A_GLD/Programs/IDN_2003_Sakernas_v01_M_v04_A_GLD_ALL.do
- GLD/IDN/IDN_2004_SAKERNAS/IDN_2004_Sakernas_v01_M_v04_A_GLD/Programs/IDN_2004_Sakernas_v01_M_v04_A_GLD_ALL.do
- GLD/IDN/IDN_2005_SAKERNAS/IDN_2005_Sakernas_v01_M_v04_A_GLD/Programs/IDN_2005_Sakernas_v01_M_v04_A_GLD_ALL.do
- GLD/IDN/IDN_2006_SAKERNAS/IDN_2006_Sakernas_v01_M_v04_A_GLD/Programs/IDN_2006_Sakernas_v01_M_v04_A_GLD_ALL.do
- GLD/IDN/IDN_2007_SAKERNAS/IDN_2007_Sakernas_v01_M_v04_A_GLD/Programs/IDN_2007_Sakernas_v01_M_v04_A_GLD_ALL.do
- GLD/IDN/IDN_2008_SAKERNAS/IDN_2008_Sakernas_v01_M_v04_A_GLD/Programs/IDN_2008_Sakernas_v01_M_v04_A_GLD_ALL.do
- GLD/IDN/IDN_2009_SAKERNAS/IDN_2009_Sakernas_v01_M_v04_A_GLD/Programs/IDN_2009_Sakernas_v01_M_v04_A_GLD_ALL.do
- GLD/IDN/IDN_2010_SAKERNAS/IDN_2010_Sakernas_v01_M_v04_A_GLD/Programs/IDN_2010_Sakernas_v01_M_v04_A_GLD_ALL.do
- GLD/IDN/IDN_2011_SAKERNAS/IDN_2011_Sakernas_v01_M_v04_A_GLD/Programs/IDN_2011_Sakernas_v01_M_v04_A_GLD_ALL.do
- GLD/IDN/IDN_2012_SAKERNAS/IDN_2012_SAKERNAS_v02_M_v03_A_GLD/Programs/IDN_2012_Sakernas_v02_M_v03_A_GLD_ALL.do
- GLD/IDN/IDN_2013_SAKERNAS/IDN_2013_Sakernas_v01_M_v04_A_GLD/Programs/IDN_2013_Sakernas_v01_M_v04_A_GLD_ALL.do
- GLD/IDN/IDN_2014_SAKERNAS/IDN_2014_Sakernas_v01_M_v04_A_GLD/Programs/IDN_2014_Sakernas_v01_M_v04_A_GLD_ALL.do
- GLD/IDN/IDN_2015_SAKERNAS/IDN_2015_Sakernas_v01_M_v04_A_GLD/Programs/IDN_2015_Sakernas_v01_M_v04_A_GLD_ALL.do
- GLD/IDN/IDN_2016_SAKERNAS/IDN_2016_Sakernas_v01_M_v05_A_GLD/Programs/IDN_2016_Sakernas_v01_M_v05_A_GLD_ALL.do
- GLD/IDN/IDN_2017_SAKERNAS/IDN_2017_Sakernas_v01_M_v06_A_GLD/Programs/IDN_2017_Sakernas_v01_M_v06_A_GLD_ALL.do
- GLD/IDN/IDN_2018_SAKERNAS/IDN_2018_Sakernas_v02_M_v04_A_GLD/Programs/IDN_2018_Sakernas_v02_M_v04_A_GLD_ALL.do
- GLD/IDN/IDN_2019_SAKERNAS/IDN_2019_Sakernas_v02_M_v04_A_GLD/Programs/IDN_2019_Sakernas_v02_M_v04_A_GLD_ALL.do
@gronert-m Hi Mario,
The `vermast' and `veralt' and the output file name have been updated according to the latest template. 
Please review and merge the patch into the main.
> Idn patch 12.12

- GLD/PAK/PAK_1992_LFS/PAK_1992_LFS_v01_M_v02_A_GLD/Programs/PAK_1992_LFS_v01_M_v02_A_GLD_ALL.do
- GLD/PAK/PAK_1999_LFS/PAK_1999_LFS_v01_M_v02_A_GLD/Programs/PAK_1999_LFS_v01_M_v02_A_GLD_ALL.do
- GLD/PAK/PAK_2001_LFS/PAK_2001_LFS_v01_M_v02_A_GLD/Programs/PAK_2001_LFS_v01_M_v02_A_GLD_ALL.do
- GLD/PAK/PAK_2003_LFS/PAK_2003_LFS_v01_M_v02_A_GLD/Programs/PAK_2003_LFS_v01_M_v02_A_GLD_ALL.do
- GLD/PAK/PAK_2005_LFS/PAK_2005_LFS_v01_M_v02_A_GLD/Programs/PAK_2005_LFS_v01_M_v02_A_GLD_ALL.do
- GLD/PAK/PAK_2007_LFS/PAK_2007_LFS_v01_M_v03_A_GLD/Programs/PAK_2007_LFS_v01_M_v03_A_GLD_ALL.do
- GLD/PAK/PAK_2008_LFS/PAK_2008_LFS_v01_M_v02_A_GLD/Programs/PAK_2008_LFS_v01_M_v02_A_GLD_ALL.do
- GLD/PAK/PAK_2009_LFS/PAK_2009_LFS_v01_M_v02_A_GLD/Programs/PAK_2009_LFS_v01_M_v02_A_GLD_ALL.do
- GLD/PAK/PAK_2010_LFS/PAK_2010_LFS_v01_M_v02_A_GLD/Programs/PAK_2010_LFS_v01_M_v02_A_GLD_ALL.do
- GLD/PAK/PAK_2012_LFS/PAK_2012_LFS_v01_M_v02_A_GLD/Programs/PAK_2012_LFS_v01_M_v02_A_GLD_ALL.do
- GLD/PAK/PAK_2013_LFS/PAK_2013_LFS_v01_M_v03_A_GLD/Programs/PAK_2013_LFS_v02_M_v01_A_GLD_ALL.do
- GLD/PAK/PAK_2013_LFS/PAK_2013_LFS_v02_M_v01_A_GLD/Programs/PAK_2013_LFS_v02_M_v01_A_GLD_ALL.do
- GLD/PAK/PAK_2014_LFS/PAK_2014_LFS_v01_M_v02_A_GLD/Programs/PAK_2014_LFS_v01_M_v02_A_GLD_ALL.do
- GLD/PAK/PAK_2017_LFS/PAK_2017_LFS_v01_M_v03_A_GLD/Programs/PAK_2017_LFS_v01_M_v03_A_GLD_ALL.do
- GLD/PAK/PAK_2018_LFS/PAK_2018_LFS_v01_M_v02_A_GLD/Programs/PAK_2018_LFS_v01_M_v02_A_GLD_ALL.do
- GLD/PAK/PAK_2020_LFS/PAK_2020_LFS_v01_M_v02_A_GLD/Programs/PAK_2020_LFS_v01_M_v02_A_GLD_ALL.do
- Support/D - Q Checks/Single survey checks/Template_Q_Checks.do
Hi Mario @gronert-m,
I have corrected the master data issue of 2013. In addition, I thought it would be an opportunity to update the directories and comment title format for Pakistan as well. I also noticed that all original variables such as `industrycat_orig` and `occup_orig` are not coded correctly as I set some conditions (i.e. only assign values to whose `lstatus` is 1), which do not maintain the original values in the raw data. Therefore, you can see that for other years I also created new alt versions and, accordingly, folders. 
But I do not make any essential changes that would impact the results. 
Let me know if you have any questions.
> Pak patch 2.8

- GLD/BRA/BRA_1981_PNAD/BRA_1981_PNAD_v01_M_v02_A_GLD/Programs/BRA_1981_PNAD_V01_M_V02_A_GLD_ALL.do
- GLD/BRA/BRA_1982_PNAD/BRA_1982_PNAD_v01_M_v02_A_GLD/Programs/BRA_1982_PNAD_V01_M_V02_A_GLD_ALL.do
- GLD/BRA/BRA_1983_PNAD/BRA_1983_PNAD_v01_M_v02_A_GLD/Programs/BRA_1983_PNAD_V01_M_V02_A_GLD_ALL.do
- GLD/BRA/BRA_1984_PNAD/BRA_1984_PNAD_v01_M_v02_A_GLD/Programs/BRA_1984_PNAD_V01_M_V02_A_GLD_ALL.do
- GLD/BRA/BRA_1985_PNAD/BRA_1985_PNAD_v01_M_v02_A_GLD/Programs/BRA_1985_PNAD_V01_M_V02_A_GLD_ALL.do
- GLD/BRA/BRA_1986_PNAD/BRA_1986_PNAD_v01_M_v02_A_GLD/Programs/BRA_1986_PNAD_V01_M_V02_A_GLD_ALL.do
- GLD/BRA/BRA_1987_PNAD/BRA_1987_PNAD_v01_M_v02_A_GLD/Programs/BRA_1987_PNAD_V01_M_V02_A_GLD_ALL.do
- GLD/BRA/BRA_1988_PNAD/BRA_1988_PNAD_v01_M_v02_A_GLD/Programs/BRA_1988_PNAD_V01_M_V02_A_GLD_ALL.do
- GLD/BRA/BRA_1989_PNAD/BRA_1989_PNAD_v01_M_v02_A_GLD/Programs/BRA_1989_PNAD_V01_M_V02_A_GLD_ALL.do
- GLD/BRA/BRA_1990_PNAD/BRA_1990_PNAD_v01_M_v02_A_GLD/Programs/BRA_1990_PNAD_V01_M_V02_A_GLD_ALL.do
whours for 1981-1990 was for second job, not primary
> Update BRA whours

- GLD/CHL/CHL_2015_CASEN/CHL_2015_CASEN_V01_M_V06_A_GLD/Programs/CHL_2015_CASEN_V01_M_V06_A_GLD_ALL.do
- GLD/CHL/CHL_2017_CASEN/CHL_2017_CASEN_V01_M_V06_A_GLD/Programs/CHL_2017_CASEN_V01_M_V06_A_GLD_ALL.do
correct empstat, ocusec for 2015, 2017
> update CHL empstat, ocusec

- GLD/PHL/PHL_2016_LFS/PHL_2016_LFS_v01_M_v05_A_GLD/Programs/PHL_2016_LFS_V01_M_V05_A_GLD_ALL.do
- GLD/PHL/PHL_2017_LFS/PHL_2017_LFS_v01_M_v04_A_GLD/Programs/PHL_2017_LFS_V01_M_V04_A_GLD_ALL.do
- GLD/PHL/PHL_2018_LFS/PHL_2018_LFS_v01_M_v04_A_GLD/Programs/PHL_2018_LFS_V01_M_V04_A_GLD_ALL.do
- GLD/PHL/PHL_2019_LFS/PHL_2019_LFS_V01_M_V05_A_GLD/Programs/PHL_2019_LFS_V01_M_V05_A_GLD_ALL.do
* Correct subnatid for regions 4A and 4B
* Include the short lived Negros Island Region into the regions it was part of, went back to.
> Update PHL subnatid1

- Support/B - Country Survey Details/Readme.md
Linked picture had old path, image not showing
> update CSD Readme

- GLD/CHL/CHL_2003_CASEN/CHL_2003_CASEN_V01_M_V05_A_GLD/Programs/CHL_2003_CASEN_V01_M_V05_A_GLD_ALL.do
- GLD/COL/COL_2007_GEIH/COL_2007_GEIH_V01_M_V02_A_GLD/Programs/COL_2007_GEIH_V01_M_V02_A_GLD.do
- GLD/COL/COL_2008_GEIH/COL_2008_GEIH_V01_M_V02_A_GLD/Programs/COL_2008_GEIH_V01_M_V02_A_GLD.do
From looking at JOIN, noted small changes in the vars underlying the informal concept.
> Update from join

- Support/D - Q Checks/Single survey checks/Helper_programs_1.5/A1.01_prepare_GLD.do
- Support/D - Q Checks/Single survey checks/Helper_programs_1.5/B2.02_ext_ddB_GLD.do
1. Add time to the folder name. It seems that the Q Checks can't be run on the same day without deleting the existing output folder. Adding time information avoids the complications regarding overwriting existing folders.
2. Updates on pulling data when data is not there
> Proposed changes

- GLD/MNG/MNG_2019_LFS/MNG_2019_LFS_V01_M_V02_A_GLD/Programs/MNG_2019_LFS_V01_M_V02_A_GLD_ALL.do
- GLD/MNG/MNG_2020_LFS/MNG_2020_LFS_V01_M_V02_A_GLD/Programs/MNG_2020_LFS_V01_M_V02_A_GLD_ALL.do
- GLD/MNG/MNG_2021_LFS/MNG_2021_LFS_V01_M_V02_A_GLD/Programs/MNG_2021_LFS_V01_M_V02_A_GLD_ALL.do
- GLD/MNG/MNG_2022_LFS/MNG_2022_LFS_V01_M_V02_A_GLD/Programs/MNG_2022_LFS_V01_M_V02_A_GLD_ALL.do
Small updates for MNG 2019-2022
> Update whours, socialsec

- Support/D - Q Checks/Survey series checks/function_load_df.R
- Support/D - Q Checks/Survey series checks/process_time_series.R
Change from binary wap yes or no argument to allowing user to set min, max age.
> Update load_df function

- GLD/IND/IND_2009_EUS/IND_2009_EUS_V01_M_V04_A_GLD/Programs/IND_2009_EUS_V01_M_V04_A_GLD_ALL.do
- GLD/IND/IND_2011_EUS/IND_2011_EUS_V01_M_V04_A_GLD/Programs/IND_2011_EUS_V01_M_V04_A_GLD_ALL.do
socialsec and contract were limited at the 12 month recall to lstatus != 1 instead of lstatus_year != 1. This is now corrected.
> Update 2009, 2011

- Support/D - Q Checks/Single survey checks/Helper_programs_1.5/A1.01_prepare_GLD.do
- Support/D - Q Checks/Single survey checks/Helper_programs_1.5/B1.04_Format_Checks_GLD.do
- Support/D - Q Checks/Single survey checks/Helper_programs_1.5/B4.01_bivariate_GLD.do
Changes:
1. Replace to zero if industry codes are missing before add operations performed
2. Create a global for current year
3. Revise check for int_year so that it is wrt current year and not 2021
> Bivariate update

- Support/D - Q Checks/Single survey checks/Helper_programs_1.5/B2.03_ext_ddC_GLD.do
what was monthly was labelled as weekly
> Small typo in comment in B2.03_ext_ddC_GLD.do

- Support/B - Country Survey Details/PAK/LFS/Correspondence_National_International_Classifications.md
table in correspondences between national / international said some versions where isco 88 when they are isco 08. Corrected.
> Small correction to ISCO version

- GLD/GMB/GMB_2018_LFS/GMB_2018_LFS_V01_M_V02_A_GLD/Programs/GMB_2018_LFS_V01_M_V02_A_GLD_ALL.do
- GLD/GMB/GMB_2023_LFS/GMB_2023_LFS_V01_M_V02_A_GLD/Programs/GMB_2023_LFS_V01_M_V02_A_GLD_ALL.do
- Support/A - Guides and Documentation/GLD Manual Files/Labor.md
Add V2 to GMB 2018, 2023 to correct ocusec, add in the manual the explanation that if info only for employees, assume the self-employed are in the private sector.
> Update GMB, Manual

- GLD/ETH/ETH_2013_LFS/ETH_2013_LFS_V01_M_V02_A_GLD/Programs/ETH_2013_LFS_V01_M_V02_A_GLD_ALL.do
- GLD/ZWE/ZWE_2019_LFS/ZWE_2019_LFS_V01_M_V02_A_GLD/Programs/ZWE_2019_LFS_V01_M_V02_A_GLD_ALL.do
- GLD/ZWE/ZWE_2021_QLFS/ZWE_2021_QLFS_V01_M_V02_A_GLD/Programs/ZWE_2021_QLFS_V01_M_V02_A_GLD_ALL.do
- GLD/ZWE/ZWE_2022_QLFS/ZWE_2022_QLFS_V01_M_V02_A_GLD/Programs/ZWE_2022_QLFS_V01_M_V02_A_GLD_ALL.do
Updated ZWE (2019, 2021, 2022) and ETH (2013) based on issues noted on ocusec.
> Update ZWE ETH

- GLD/ARM/ARM_2014_LFS/ARM_2014_LFS_V01_M_V02_A_GLD/Programs/ARM_2014_LFS_V01_M_V02_A_GLD_ALL.do
- GLD/ARM/ARM_2015_LFS/ARM_2015_LFS_V01_M_V02_A_GLD/Programs/ARM_2015_LFS_V01_M_V02_A_GLD_ALL.do
- GLD/ARM/ARM_2016_LFS/ARM_2016_LFS_V01_M_V02_A_GLD/Programs/ARM_2016_LFS_V01_M_V02_A_GLD_ALL.do
- GLD/ARM/ARM_2017_LFS/ARM_2017_LFS_V01_M_V02_A_GLD/Programs/ARM_2017_LFS_V01_M_V02_A_GLD_ALL.do
- GLD/ARM/ARM_2018_LFS/ARM_2018_LFS_V01_M_V02_A_GLD/Programs/ARM_2018_LFS_V01_M_V02_A_GLD_ALL.do
- GLD/ARM/ARM_2019_LFS/ARM_2019_LFS_V01_M_V02_A_GLD/Programs/ARM_2019_LFS_V01_M_V02_A_GLD_ALL.do
- GLD/ARM/ARM_2020_LFS/ARM_2020_LFS_V01_M_V02_A_GLD/Programs/ARM_2020_LFS_V01_M_V02_A_GLD_ALL.do
- GLD/ARM/ARM_2021_LFS/ARM_2021_LFS_V01_M_V02_A_GLD/Programs/ARM_2021_LFS_V01_M_V02_A_GLD_ALL.do
- GLD/ARM/ARM_2022_LFS/ARM_2022_LFS_V01_M_V02_A_GLD/Programs/ARM_2022_LFS_V01_M_V02_A_GLD_ALL.do
> add V02 to LF

- Support/A - Guides and Documentation/GLD Manual Files/Using the GLD.md
Make how to cite a ## level header
> Update Using the GLD.md

- GLD/CMR/CMR_2021_EESI/CMR_2021_EESI_V01_M_V02_A_GLD/Programs/CMR_2021_EESI_V01_M_V02_A_GLD_ALL.do
Correction on the weight variable used
> Add CMR 2021 V02 A

- GLD/BGD/BGD_2022_QLFS/BGD_2022_QLFS_V01_M_V02_A_GLD/Programs/BGD_2022_QLFS_V01_M_V02_A_GLD.do
* Correction on a number of missing occupations when industry is know, mostly for own consumption. Reduces missing info from ~30K to ~10K.
> Add V02 to BGD 2022 LFS

- Support/D - Q Checks/Single survey checks/Helper_programs_1.5/B2.01_ext_ddA_GLD.do
- Support/D - Q Checks/Single survey checks/Helper_programs_1.5/B2.02_ext_ddB_GLD.do
- Support/D - Q Checks/Single survey checks/Helper_programs_1.5/B2.03_ext_ddC_GLD.do
Errors stopping code if no WDI info
> Correct if process if WDI not available

- GLD/ARM/ARM_2023_LFS/ARM_2023_LFS_V01_M_V02_A_GLD/Programs/ARM_2023_LFS_V01_M_V02_A_GLD_ALL.do
Correct for absent respondents (others filled out for them, have only lstatus)
> Arm 2023 update

- GLD/ARM/ARM_2014_LFS/ARM_2014_LFS_V01_M_V04_A_GLD/Programs/ARM_2014_LFS_V01_M_V04_A_GLD_ALL.do
- GLD/ARM/ARM_2015_LFS/ARM_2015_LFS_V01_M_V04_A_GLD/Programs/ARM_2015_LFS_V01_M_V04_A_GLD_ALL.do
- GLD/ARM/ARM_2016_LFS/ARM_2016_LFS_V01_M_V04_A_GLD/Programs/ARM_2016_LFS_V01_M_V04_A_GLD_ALL.do
- GLD/ARM/ARM_2017_LFS/ARM_2017_LFS_V01_M_V04_A_GLD/Programs/ARM_2017_LFS_V01_M_V04_A_GLD_ALL.do
- GLD/ARM/ARM_2018_LFS/ARM_2018_LFS_V01_M_V04_A_GLD/Programs/ARM_2018_LFS_V01_M_V04_A_GLD_ALL.do
- GLD/ARM/ARM_2019_LFS/ARM_2019_LFS_V01_M_V04_A_GLD/Programs/ARM_2019_LFS_V01_M_V04_A_GLD_ALL.do
- GLD/ARM/ARM_2020_LFS/ARM_2020_LFS_V01_M_V04_A_GLD/Programs/ARM_2020_LFS_V01_M_V04_A_GLD_ALL.do
- GLD/ARM/ARM_2021_LFS/ARM_2021_LFS_V01_M_V04_A_GLD/Programs/ARM_2021_LFS_V01_M_V04_A_GLD_ALL.do
- GLD/ARM/ARM_2022_LFS/ARM_2022_LFS_V01_M_V05_A_GLD/Programs/ARM_2022_LFS_V01_M_V05_A_GLD_ALL.do
- GLD/ARM/ARM_2023_LFS/ARM_2023_LFS_V01_M_V03_A_GLD/Programs/ARM_2023_LFS_V01_M_V03_A_GLD_ALL.do
* All years include isic_v for ISIC Rev 4
* 2022 and 2023 include unitwage as per E16
> ARM update

- GLD/MEX/MEX_2020_ENOE/MEX_2020_ENOE_V03_M_V02_A_GLD/Programs/MEX_2020_ENOE_V03_M_V02_A_GLD_ALL.do
- GLD/TUN/TUN_2000_ENPE/TUN_2000_ENPE_V01_M_V02_A_GLD/Programs/TUN_2000_ENPE_V01_M_V02_A_GLD_ALL.do
* Correct weight on TUN 2000 (missing for negative weights)
* Make weight_q = weight in ENOE 2020 (where we only had one quarter data).
> Add differences
